include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    public_member_api_docs: true
    avoid_dynamic_calls: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    deprecated_member_use_from_same_package: true
